[build]
# rustflags = ["-g"]
target = ["riscv64gc-unknown-none-elf", "x86_64-unknown-none"]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/arch/riscv64/link.ld",
    "-C", "link-arg=--omagic",
]

